server:
  port : 9091
spring:
  server:
    protocol: http
    url: 0.0.0.0:9091
  h2:
    mem:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:/db/migration
  hibernate:
    connection:
      url: jdbc:h2:mem:test
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver